# Generated by Django 4.2.6 on 2023-10-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('accountnumber', models.IntegerField(null=True)),
                ('phone', models.IntegerField(unique=True)),
                ('amount', models.IntegerField(null=True)),
                ('from_phone', models.IntegerField(null=True)),
                ('to_phone', models.IntegerField(null=True)),
                ('t_amount', models.IntegerField(null=True)),
                ('dt', models.CharField(max_length=30)),
            ],
        ),
    ]
