# Generated by Django 4.2.6 on 2023-10-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_phone', models.IntegerField(null=True)),
                ('to_phone', models.IntegerField(null=True)),
                ('t_amount', models.IntegerField(null=True)),
                ('dt', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='acc',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='acc',
            name='from_phone',
        ),
        migrations.RemoveField(
            model_name='acc',
            name='t_amount',
        ),
        migrations.RemoveField(
            model_name='acc',
            name='to_phone',
        ),
    ]
